### ISSUE TITLE
PVR channels widget doesn't pass other artwork types (e.g. poster / fanart).

### ISSUE THREAD

**Issue by jurialmunkey** [marcelveldt/script.skin.helper.widgets#20]
Had a few reports that PVR channels widgets are **only** passing through the thumb image that is defined in managed artwork. I checked and it seems that even if posters / fanart etc are manually defined inside the MyPVR* windows the widgets do not fill ListItem.Art(poster) or ListItem.Art(fanart) etc.

Are these possible to add?

**Comment by marcelveldt** [comment]
Did you notice that in the settings for this add-on you can enable the artwork lookups ?

**Comment by jurialmunkey** [comment]
I had it enabled when I was testing. 
Using the Demo PVR add-on, I set an item manually inside TVChannels window. The artwork displays correctly there. In the widget, the background fanart using the Skin Helper window property will show correctly for the item so it is being looked up, but inside the container ListItem.Art(fanart) is blank. Are the listitem properties only filled by automatic look-ups and not manually set ones?

**Comment by dazedcrazy** [comment]
It gets all the correct images
![vflxkw7](https://user-images.githubusercontent.com/9027988/30806356-652d3588-a1ed-11e7-9b74-41c4c524cf03.png)
But only displays the thumb 
![wnn91cz](https://user-images.githubusercontent.com/9027988/30806377-77046a88-a1ed-11e7-8173-cda1c2fd4d14.png)
No matter the widget type
![hlqydma](https://user-images.githubusercontent.com/9027988/30806481-ceff9528-a1ed-11e7-95d8-575ffa24d613.png)
![xcghued](https://user-images.githubusercontent.com/9027988/30806508-f937abdc-a1ed-11e7-9bff-b035d8daf5ee.png)

**Comment by dazedcrazy** [comment]
This is where it makes things look really stupid when it uses the thumb instead of the poster
Images it gets
![lptlrtg](https://user-images.githubusercontent.com/9027988/33170478-47c3f85c-d040-11e7-9ed2-4945f4604a93.png)
And image it uses
![wyskd71](https://user-images.githubusercontent.com/9027988/33170472-403ba56c-d040-11e7-82b3-0b7500cfca75.png)

**Comment by natevoci** [comment]
Hi @jurialmunkey 

I've noticed in the code that the poster and fanart art do get set from the `get_pvr_artwork` call (if "Enable artwork lookups for PVR" setting is on). The relevent code is in %appdata/Kodi/addons/script.skin.helper.widgets/resources/lib/pvr.py in the `process_channel` function,

```
            if self.enable_artwork:
                self.metadatautils.extend_dict(
                    item, self.metadatautils.get_pvr_artwork(
                        item["title"], channelname, item["genre"]))
```

but it then the art property gets replaced later in that function
```
        if channellogo:
            item["art"] = {"thumb": channellogo}
```

Perhaps try changing it so that it uses the existing art object if it exists, and only sets the thumb property if it's missing. Something like this (untested)
```
        if channellogo:
            if not item.get("art"):
                item["art"] = {}
            if not item["art"].get("thumb"):
                item["art"]["thumb"] = channellogo
```

Edit: Fixed a missing : in the code snippet
