### ISSUE TITLE
PVR channel group widget duplicates after refresh

### ISSUE THREAD

**Issue by ragga22** [marcelveldt/script.skin.helper.widgets#24]
Hello my friend,

I use the Skin helper service to add PVR Channel groups as widgets.

It often starts off displaying the groups correctly, but after an automatic widget refresh the groups become duplicated (both groups display the exact same channels). When that happens, even browsing the groups through the the Skin helper service directly via the addon section, the PVR groups will default to showing the same chanels. Browsing the groups through the simple IPTV client is fine and the groups display correctly there.

The issue is generally triggered by the changing of the widget's settings (banners,size etc.) or by the automatic built in widget refresh or by a manual refresh as well (the last 2 methods do not always cause the problem but eventually will).

To fix it, Kodi needs to be restarted (this will generally work but sometimes more than one restart is necessary).

Tried this on 3 different Windows setups as well as on 2 Android devices.. exact same behaviour.

You can see below what the problem looks like, one pic shows the correct widgets with the right channels, and the other the same widgets but now the channels are duplicated from one of the other groups. Running on krypton 17.4 - titan 3.7.63 - skin.helper.widgets 1.0.35 (tried 1.0.36 as well)

![screenshot003](https://user-images.githubusercontent.com/32957470/31854094-0b1ec6f2-b68c-11e7-9bc7-eedc0c7ca20a.png)
![screenshot004](https://user-images.githubusercontent.com/32957470/31854095-0b36e4ee-b68c-11e7-9309-97a08b490997.png)

**Comment by ragga22** [comment]
Is marcel still moderating his project ?

**Comment by marcelveldt** [comment]
yes, but I'm a bit busy atm

**Comment by ragga22** [comment]
Is anyone else able to comment ?

**Comment by ragga22** [comment]
hellooo?

**Comment by marcelveldt** [comment]
sorry, I don't have an answer for you atm. Feel free to submit a PR with the fix.

**Comment by neilimixamo** [comment]
Hi marcel, Hi patrick,

First of all, I’d like to **thank you for your wonderful tool** which greatly improves our use of Kodi. So, even if ragga22 described the issue very well a while ago, let me explain it back again in my own words.

Let’s say **I have 3 channel groups**** (previously generated in the group manager of Kodi LiveTv settings) named "2", "3" & "4" **and create,** through the skin settings, some **widgets linked to the** generic channel **entries** automatically **generated in** your **addon/PVR folder**, like "Recently played TV channels", "TV Channels : All channels", "TV Channels: 2", "TV Channels: 3", "TV Channels: 4"

![image](https://user-images.githubusercontent.com/43101688/45260017-3c8ec780-b3db-11e8-978b-d4ff971b3189.png)

Once those **widgets created**, going back to the home screen leads to a refresh wich makes them appear correctly, each widget showing his right name and right inside-channels **but,** **after clicking randomly on one of them, the other widgets instantly transform their content to simulate the first opened widget** (without changing their original name). 

This issue is 100% reproductible and unfortunately ruins the maximum user confort you dreamt of, while spending hours creating this very nice addon (tested with w10, kodi 17.6 & 18beta, skin estuarymodv2 & titanmod, PVR IPTV Simple Client). That's why I would like to encourage you accomplishing perfection.

I first thought it maybe was a conflict with the skin.shortcuts refreshing action but then noticed a **similar reaction inside your addon(1.0.38)**/PVR/channels entries. I mean, just opening « TV Channels: 3 » and directly going back to the parent folder (without even playing any channel) will make the other channelgroups act like this first open group by simulating his path and channels.

So, in my opinion, it **seems like the addon correctly creates multiple and specific widgetpaths to channel groups but is not able to memorize all of them.** Does it simply sticks to the first path or does it forget the other ones? I don't know... Or could it just be related to the reload property ? I’m personally not a coder at all but maybe that changing something in this part of **« ressources/lib/pvr.py »** could resolve the problem, what do you think about that? 

![image](https://user-images.githubusercontent.com/43101688/45259985-01d85f80-b3da-11e8-9611-b3674e292481.png)

I'm looking forward to seeing those great pvr group widgets working fine on my kodi everyday use setup even if I can reasonably imagine that you guys are very busy. Anyway, hope it will help you find a solution soon or later. **Thanks** in advance.

**Comment by ragga22** [comment]
still here ?

**Comment by neilimixamo** [comment]
Yeah, i would be pleased to hear an answer too. Thanks 👍

**Comment by Robro81** [comment]
I'm curious how you got this working in the first place. I don't get the options of the channel groups at all, is there a certain variable that I should add? 
This is the only option I have and it let's me see the channels from the first group in the group list. But I want to see the 7th group with channels 

plugin://script.skin.helper.widgets/?action=channels&mediatype=pvr&reload=$INFO[Window(Home).Property(widgetreload2)

**Comment by Xaque8787** [comment]
Having the same issue as neilimixamo describes above. Anyone find a fix to this issue?
